export const SHOW_CATEGORY = 'SHOW_CATEGORY';
export const SHOW_EVENT = 'SHOW_EVENT';
export const SHOW_ONE_CATEGORY = 'SHOW_ONE_CATEGORY';
export const SHOW_ONE_EVENT = 'SHOW_ONE_EVENT';
export const SHOW_ORDER = 'SHOW_ORDER';